# docker-compose.yml
version: '3'
services:
  database:
    image:postgis/postgis:12-master 
    restart: unless-stopped
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "127.0.0.1:5445:5432"
volumes:
  database-data: # named volumes can be managed easier using docker-compose
  