# Generated by Django 3.1 on 2021-11-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_garden_members'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='garden',
            field=models.ManyToManyField(to='gardens.Garden'),
        ),
    ]
