# Generated by Django 3.1 on 2021-12-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_auto_20211202_1740'),
        ('users', '0003_auto_20211201_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_logged_in',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='gardenmembership',
            name='role',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Member')], default='2', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='garden',
            field=models.ManyToManyField(blank=True, to='gardens.Garden'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
