# Generated by Django 3.1 on 2021-12-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='email',
            field=models.CharField(max_length=250),
        ),
    ]
