# Generated by Django 3.1 on 2021-11-28 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('venue', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('garden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gardens.garden')),
            ],
        ),
    ]
