# Generated by Django 3.1 on 2021-11-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='count',
        ),
        migrations.AddField(
            model_name='garden',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('TOOLS', 'Tools'), ('SEEDS', 'Seeds'), ('FERTILIZERS', 'Fertilizers'), ('COMPOST', 'Compost'), ('CONSTRUCTION_MATERIALS', 'Construction_materials'), ('GARDENS', 'Gardens'), ('OTHERS', 'Others')], default='TOOLS', max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_status',
            field=models.CharField(choices=[('AVAILABLE FOR BORROWING', 'Available for borrowing'), ('BORROWED', 'Borrowed'), ('AVAILABLE FOR DONATION', 'Available for donation')], default='AVAILABLE', max_length=50),
        ),
    ]
