# Generated by Django 3.1 on 2021-12-02 17:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_garden_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='geom_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='garden',
            name='geom_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='garden',
            name='primary_purpose',
            field=models.CharField(choices=[('GARDEN', 'Garden'), ('RESOURCES', 'Resources')], default='RESOURCES', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('TOOLS', 'Tools'), ('SEEDS', 'Seeds'), ('FERTILIZERS', 'Fertilizers'), ('COMPOST', 'Compost'), ('CONSTRUCTION_MATERIALS', 'Construction_materials'), ('GARDENS', 'Gardens'), ('OTHERS', 'Others')], default='TOOLS', max_length=255),
        ),
        migrations.AlterField(
            model_name='garden',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='garden',
            name='latitude',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='garden',
            name='longitude',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='garden',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='garden',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_status',
            field=models.CharField(choices=[('AVAILABLE FOR BORROWING', 'Available for borrowing'), ('BORROWED', 'Borrowed'), ('AVAILABLE FOR DONATION', 'Available for donation')], default='AVAILABLE', max_length=255),
        ),
    ]
