# Generated by Django 3.1 on 2021-12-19 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardens', '0005_auto_20211219_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourceborrowing',
            old_name='user_id',
            new_name='borrower_id',
        ),
        migrations.AddField(
            model_name='resource',
            name='lender_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
