# Generated by Django 3.1 on 2021-12-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_auto_20211205_1004'),
        ('gardens', '0006_auto_20211219_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='garden',
            name='crops',
            field=models.ManyToManyField(blank=True, to='crops.Crop'),
        ),
    ]
