# Generated by Django 3.1 on 2021-12-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_auto_20211202_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
