# Generated by Django 3.1 on 2022-01-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0007_auto_20211231_2258'),
        ('crops', '0003_auto_20211205_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='gardens',
            field=models.ManyToManyField(to='gardens.Garden'),
        ),
    ]
