# Generated by Django 3.1 on 2021-11-28 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(choices=[('TOOLS', 'Tools'), ('SEEDS', 'Seeds'), ('FERTILIZERS', 'Fertilizers'), ('COMPOST', 'Compost'), ('CONSTRUCTION_MATERIALS', 'Construction_materials'), ('GARDENS', 'Gardens'), ('OTHERS', 'Others')], default='TOOLS', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('garden_id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField(max_length=10)),
                ('latitude', models.FloatField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255, null=True)),
                ('crops', models.ManyToManyField(to='crops.Crop')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_status', models.CharField(choices=[('AVAILABLE FOR BORROWING', 'Available for borrowing'), ('BORROWED', 'Borrowed'), ('AVAILABLE FOR DONATION', 'Available for donation')], default='AVAILABLE', max_length=50)),
                ('resource_name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gardens.category')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gardens.garden')),
            ],
        ),
    ]
