# Generated by Django 3.1 on 2021-11-28 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='members',
            field=models.ManyToManyField(related_name='gardens', through='users.GardenMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
