# Generated by Django 3.1 on 2022-01-25 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardens', '0008_auto_20220122_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='gardens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='garden',
            name='primary_purpose',
            field=models.CharField(choices=[('GARDEN', 'Garden'), ('RESOURCES', 'Resources')], default='RESOURCES', max_length=250),
        ),
    ]
