{
    "resource_status": "AVAILABLE FOR BORROWING",
    "resource_name": "Spade",
    "category": 1,
    "date_created": "2021-12-04T15:55:52.989250Z",
    "return_date": "2021-12-16T12:00:00Z",
    "garden": 2
  }