{
    "resource_status": "AVAILABLE FOR DONATION",
    "resource_name": "Horse Poop",
    "description": "Horse manure is a good source of nutrients and a popular additive to many home gardens. Horse dung manure makes the compost pile become super charged and also increases soil fertility, regeneration, and high quality yields. It is a suitable and inexpensive fertilizer for plants",
    "date_created": "2022-01-16T23:46:42.564029Z",
    "return_date": "2022-20-16T23:46:42.564029Z",
    "category": 3,
    "garden": 5,
    "lender_id": 4
  }