{ 
    "longitude": 51.95406, 
    "latitude": 7.62516, 
    "name": "Gemeinschaftsgarten Querbeet", 
    "description": "The garden consists of 16 raised beds ... 
                    The garden can be used as a meeting place ...", 
    "email": "garden-email@gmail.com", 
    "phone": "+491xxxxxxxx", 
    "address": "Josefstrasse 2", 
    "geom_point": {
        "type": "Point", 
        "coordinates": [-0.034294116776437, 0.018081666485151]
    }, 
    "geom_polygon": {
        "type": "Polygon", 
        "coordinates": [
            [
                [-0.002861015964299, 0.035667405488396], 
                [0.062141418457031, 0.039939849196801], 
                [0.029487619176507, 0.054588288657813], 
                [-0.002861015964299, 0.035667405488396]
            ]
        ]
    },        
    "primary_purpose": "GARDEN", 
    "crops": [], 
    "members": []
}

