{
    "title": "workshop",
      "description" : "urban gardens",
     "venue" : "muenster",
       "date" : "10-12-2021",
     "duration" : "2:00:00",
     "garden":"Gemeinschaftsgarten Querbeet"
}


