# Generated by Django 3.1 on 2021-11-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_auto_20211126_1424'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('1', 'Admin'), ('2', 'Member')], default='2', max_length=1)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.garden')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='garden',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='privilege',
        ),
        migrations.DeleteModel(
            name='Privilege',
        ),
        migrations.AddField(
            model_name='gardenmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
